import type { Skill } from "./skill-model";

export const BUILT_IN_SKILLS: Skill[] = [
  {
    id: "prd",
    name: "Write a PRD",
    description: "Turn a rough idea into a structured product requirements document with goals and risks.",
    prompt: "Write a concise PRD with: problem, goals, non-goals, users, user stories, metrics, rollout risks, open questions.",
    format: { structure: "Problem -> Goals -> Non-goals -> Users -> User stories -> Metrics -> Risks -> Open questions", maxWords: 600 },
    category: "Product",
    builtIn: true,
  },
  {
    id: "review",
    name: "Code Review",
    description: "Review code for correctness, edge cases, security, and readability with actionable notes.",
    prompt: "Perform a thorough code review. Call out bugs, security issues, performance, tests to add, and suggest refactors.",
    format: { structure: "Summary -> Bugs -> Security -> Performance -> Tests -> Refactors", tone: "direct and specific -- cite line numbers or patterns, not generalities" },
    category: "Engineering",
    builtIn: true,
  },
  {
    id: "eli5",
    name: "Explain Like I'm 5",
    description: "Explain complex topics using simple analogies and short sentences.",
    prompt: "Explain the topic as if to a curious beginner. Use analogies, avoid jargon, keep it short.",
    format: { maxWords: 200, tone: "warm, patient, and encouraging -- like a good teacher", structure: "One analogy -> Core idea in plain language -> One takeaway" },
    category: "Learning",
    builtIn: true,
  },
  {
    id: "debate",
    name: "Debate Both Sides",
    description: "Argue both sides fairly, then give a balanced takeaway.",
    prompt: "Present the strongest case FOR and AGAINST. Then summarize tradeoffs and what you'd recommend and why.",
    format: { structure: "FOR (3 strongest points) -> AGAINST (3 strongest points) -> Tradeoffs -> Recommendation", maxWords: 500 },
    category: "Reasoning",
    builtIn: true,
  },
  {
    id: "summarize",
    name: "Summarize",
    description: "Summarize long text into bullets with key claims and unknowns.",
    prompt: "Summarize with: key points, assumptions, risks, and a tight executive summary at the top.",
    format: { structure: "Executive summary (2 sentences) -> Key points (bullets) -> Assumptions -> Risks -> Unknowns", maxWords: 350 },
    category: "Writing",
    builtIn: true,
  },
  {
    id: "tutorial",
    name: "Create Tutorial",
    description: "Create a step-by-step tutorial with prerequisites and checkpoints.",
    prompt: "Write a tutorial with prerequisites, numbered steps, expected outputs, troubleshooting, and next steps.",
    format: { structure: "Prerequisites -> Numbered steps (each with expected output) -> Troubleshooting -> Next steps", tone: "patient and precise" },
    category: "Learning",
    builtIn: true,
  },
  {
    id: "brainstorm",
    name: "Brainstorm",
    description: "Generate diverse ideas, constraints, and evaluation criteria.",
    prompt: "Brainstorm options, include constraints, rank by impact/effort, and propose 3 next experiments.",
    format: { structure: "10 ideas (one line each) -> Top 3 ranked by impact/effort -> Constraints to watch -> 3 experiments to run next", maxWords: 400 },
    category: "Product",
    builtIn: true,
  },
  {
    id: "debug",
    name: "Debug This",
    description: "Systematically debug errors with hypotheses and minimal repro steps.",
    prompt: "Debug systematically: restate symptoms, hypotheses, quick checks, likely root cause, fix, and validation steps.",
    format: { structure: "Symptoms -> Hypotheses (ranked most->least likely) -> Quick checks -> Root cause -> Fix -> Validation", tone: "clinical and precise" },
    category: "Engineering",
    builtIn: true,
  },
  {
    id: "risk",
    name: "Risk Review",
    description: "Identify operational and product risks with mitigations.",
    prompt: "List risks (likelihood/impact), mitigations, monitoring signals, and rollback plans.",
    format: { structure: "Risk table (Risk | Likelihood | Impact | Mitigation) -> Monitoring signals -> Rollback plan", maxWords: 400 },
    category: "Product",
    builtIn: true,
  },
  {
    id: "rewrite",
    name: "Polish Writing",
    description: "Improve clarity, tone, and structure without changing meaning.",
    prompt: "Rewrite for clarity and tone. Keep meaning. Note important caveats if any.",
    format: { tone: "match the original intent but sharpen every sentence -- cut filler, strengthen verbs, tighten structure", maxWords: 400 },
    category: "Writing",
    builtIn: true,
  },
];
